name: synchronize Domain Web
# Only trigger when the build docker workflow succeeded
on:
  workflow_run:
    workflows: [ "Docker Image CI" ]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: trigger specific repo's workflow
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: NoahAmethyst
          repo: Blog-Index
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          workflow_file_name: docker.yml
          trigger_workflow: true
